name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  frontend:
    name: Frontend (Next.js)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
    - uses: pnpm/action-setup@v4
      with: 
        version: 9 #latest stable pnpm
    - run: pnpm install --frozen-lockfile=false
    - run: pnpm lint
    - run: pnpm build
  
  api:
    name: API (NestJS)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
      - run: corepack enable
      - run: pnpm install --frozen-lockfile=false
      - run: pnpm lint
      - run: pnpm build
  
  ml:
    name: ML (Python)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ml
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - run: python -m pip install --upgrade pip
      - run: pip install pytest
      - run: pytest -q tests